name: E2E tests daily
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
      - cron: "*/20 * * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        # https://github.com/cypress-io/github-action
        - name: Cypress run
          uses: cypress-io/github-action@v1
          with:
            build: yarn install
            command: yarn main:ci