name: E2E tests daily
on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]
      branches:
        - main
    schedule:
      - cron: "*/120 * * * *"
jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
       - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
          build: yarn install
          command: yarn main:ci